---
title: "exploratory"
author: "Phoebe Meyerson"
date: "2024-01-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(mapview)
library(sf)
library(sfdep)
library(tidyverse)
library(Matrix)
library(matrixcalc)
library(stargazer)
```

```{r}
data <- readRDS(here("dat_wt.rds"))

ecomap <- readRDS(here("data/ecomap.rds")) %>%
  filter(PROVINCE == "M333")

dat_list <- data %>%
  group_by(rep) %>%
  group_split()

viz_dat <- dat_list[[1]]

rm(data, dat_list)
```

```{r}
# EXPLORATORY DATA VISUALIZATIONS

# in general: should i add units to labels

# tell people in writeup that we didn't include tnt bc it didn't vary
# ggsave()
scatter <- ggplot(data = viz_dat, aes(x = tcc, y = DRYBIO)) +
  geom_point(alpha = 0.2, col = "springgreen4") +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2), 
              col = "darkgreen", lwd = 1.2) +
  labs(x = "Tree Canopy Cover (%)", y = "Dry Biomass (Tons)") +
  # facet_wrap(~SUBSECTION) + # option to do or not do this
  theme_minimal(base_size = 14)

ggsave("scatter.png", scatter)

# biomass by tnt
tnt_biomass <- ggplot(data = viz_dat, aes(x = factor(tnt), y = DRYBIO, fill = factor(tnt))) +
  geom_boxplot(alpha = 0.8, fill = c("gold1", "springgreen4")) +
  scale_x_discrete(labels = c("No Tree", "Tree")) +
  labs(x = "Tree Presence", y = "Dry Biomass (Tons)") + 
  guides(fill = FALSE) +
  theme_minimal(base_size = 14)

ggsave("tnt_biomass.png", tnt_biomass)

# tcc by tnt
ggplot(data = viz_dat, aes(x = factor(tnt), y = tcc, fill = factor(tnt))) +
  geom_boxplot(alpha = 0.8) +
  scale_fill_manual(values = c("gold1", "springgreen4"), name = "TNT") +
  labs(x = "Tree No-Tree", y = "Tree Canopy Cover") +
  # facet_wrap(~SUBSECTION) + # option to do or not do this
  theme_minimal()

# choosing linear models
lm0 <- lm(DRYBIO ~ tnt, data = viz_dat)
lm1 <- lm(DRYBIO ~ tcc, data = viz_dat)
lm2 <- lm(DRYBIO ~ tcc + tnt, data = viz_dat)
lm3 <- lm(DRYBIO ~ tcc + tnt + tcc*tnt, data = viz_dat)
lm4 <- lm(DRYBIO ~ poly(tcc, 2, raw=T) + tnt, data = viz_dat)
lm5 <- lm(DRYBIO ~ poly(tcc, 2, raw=T) + tnt + tnt*poly(tcc, 2, raw=T), data = viz_dat)
lm6 <- lm(DRYBIO ~ poly(tcc, 2, raw=T), data = viz_dat)
lm7 <- lm(DRYBIO ~ tcc^2, data = viz_dat)

stargazer(lm2, lm3, lm4, lm5, lm6, lm7, type = "text")

# tcc by subsection
avg_tcc <- viz_dat %>%
  group_by(SUBSECTION) %>%
  summarize(avg_tcc = mean(tcc),
            var_tcc = var(tcc)) %>%
  select(SUBSECTION, avg_tcc, var_tcc)

truth_tcc <- readRDS("pop_dat.rds") %>%
  group_by(SUBSECTION) %>%
  summarize(mean_tcc = mean(tcc),
            var_tcc = var(tcc))

maptcc_viz <- left_join(ecomap, avg_tcc, by = join_by(SUBSECTION))
maptcc_truth <- left_join(ecomap, truth_tcc, by = join_by(SUBSECTION))

# in viz_dat: avg
maptcc_avg <- ggplot() +
  geom_sf(data = maptcc_viz, aes(fill = avg_tcc)) +
  scale_fill_gradient(low = "gold1", high = "springgreen4", 
                      name = "Mean TCC") +
  theme_minimal(base_size = 14) +
  theme_void()

# in viz_dat: var
maptcc_var <- ggplot() +
  geom_sf(data = maptcc_viz, aes(fill = var_tcc)) +
  scale_fill_gradient(low = "gold1", high = "springgreen4", 
                      name = "TCC Variance") +
  theme_minimal(base_size = 14) +
  theme_void()

ggsave("maptcc_avg.png", maptcc_avg)
ggsave("maptcc_var.png", maptcc_var)

# in truth: avg
ggplot() +
  geom_sf(data = maptcc_truth, aes(fill = mean_tcc)) +
  scale_fill_gradient(low = "gold1", high = "springgreen4", 
                      name = "Mean TCC") +
  theme_minimal() + theme_void()

# in truth: var
ggplot() +
  geom_sf(data = maptcc_truth, aes(fill = var_tcc)) +
  scale_fill_gradient(low = "gold1", high = "springgreen4", 
                      name = "TCC Variance") +
  theme_minimal() + theme_void()

```

